In [3]:

from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# 1. LOCATE AND LOAD THE DATASET
# ============================================================

cwd = Path.cwd()

possible_paths = [
    cwd / "data" / "kepler_cleaned.csv",
    cwd / "kepler-exoplanet-ml" / "data" / "kepler_cleaned.csv",
    cwd.parent / "data" / "kepler_cleaned.csv",
]

file_path = next(
    (path.resolve() for path in possible_paths if path.is_file()),
    None
)

if file_path is None:
    raise FileNotFoundError(
        f"Could not find kepler_cleaned.csv.\n"
        f"Current working directory: {cwd}\n"
        "Expected the CSV inside kepler-exoplanet-ml/data/."
    )

print("Dataset path:", file_path)

df = pd.read_csv(file_path)

print("\nDataset loaded successfully!")
print("Dataset shape:", df.shape)
display(df.head())

# ============================================================
# 2. PREPARE FEATURES AND TARGET
# ============================================================

if "target" not in df.columns:
    raise ValueError(
        "The dataset must contain a column named 'target'."
    )

X = df.drop(columns=["target"])
y = df["target"]

print("\nNumber of features:", X.shape[1])
print("Number of samples:", X.shape[0])

print("\nTarget distribution:")
print(y.value_counts())

# ============================================================
# 3. SPLIT INTO TRAINING AND TESTING DATA
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# ============================================================
# 4. INITIALIZE AND TRAIN THE DECISION TREE
# ============================================================

dt = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt.fit(X_train, y_train)

print("\nDecision Tree training completed successfully!")

# ============================================================
# 5. GENERATE PREDICTIONS
# ============================================================

preds = dt.predict(X_test)

# ============================================================
# 6. EVALUATE MODEL PERFORMANCE
# ============================================================

accuracy = accuracy_score(y_test, preds)

print("\n" + "=" * 50)
print("DECISION TREE MODEL EVALUATION")
print("=" * 50)

print(f"\nAccuracy: {accuracy:.4f}")
print(f"Accuracy percentage: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        preds,
        zero_division=0
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, preds))

print("\nModel evaluation completed!")

Dataset path: C:\Users\suyas\OneDrive\GIT\ML_LEARNING\kepler-exoplanet-ml\data\kepler_cleaned.csv

Dataset loaded successfully!
Dataset shape: (9564, 42)

,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag,target
0,1.000,0,0,0,0,9.488036,2.780000e-05,-2.780000e-05,170.538750,0.002160,...,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1
1,0.969,0,0,0,0,54.418383,2.480000e-04,-2.480000e-04,162.513840,0.003520,...,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1
2,0.000,0,0,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,1
3,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0
4,1.000,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1

Number of features: 41
Number of samples: 9564

Target distribution:
target
0    4840
1    4724
Name: count, dtype: int64

Training samples: 7651
Testing samples: 1913

Decision Tree training completed successfully!

==================================================
DECISION TREE MODEL EVALUATION
==================================================

Accuracy: 0.9728
Accuracy percentage: 97.28%

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       968
           1       0.95      1.00      0.97       945

    accuracy                           0.97      1913
   macro avg       0.97      0.97      0.97      1913
weighted avg       0.97      0.97      0.97      1913

Confusion Matrix:
[[917  51]
 [  1 944]]

Model evaluation completed!

In [4]:

from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# 1. LOCATE AND LOAD THE DATASET
# ============================================================

cwd = Path.cwd()

possible_paths = [
    cwd / "data" / "kepler_cleaned.csv",
    cwd / "kepler-exoplanet-ml" / "data" / "kepler_cleaned.csv",
    cwd.parent / "data" / "kepler_cleaned.csv",
]

file_path = next(
    (path.resolve() for path in possible_paths if path.is_file()),
    None
)

if file_path is None:
    raise FileNotFoundError(
        f"Could not find kepler_cleaned.csv.\n"
        f"Current working directory: {cwd}\n"
        "Expected the CSV inside kepler-exoplanet-ml/data/."
    )

print("Dataset path:", file_path)

df = pd.read_csv(file_path)

print("\nDataset loaded successfully!")
print("Dataset shape:", df.shape)
display(df.head())

# ============================================================
# 2. PREPARE FEATURES AND TARGET
# ============================================================

if "target" not in df.columns:
    raise ValueError(
        "The dataset must contain a column named 'target'."
    )

X = df.drop(columns=["target"])
y = df["target"]

print("\nNumber of features:", X.shape[1])
print("Number of samples:", X.shape[0])

# ============================================================
# 3. SPLIT INTO TRAINING AND TESTING DATA
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# ============================================================
# 4. STANDARDIZE THE FEATURES
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nFeature scaling completed!")

# ============================================================
# 5. INITIALIZE AND TRAIN THE SVM MODEL
# ============================================================

svm = SVC(
    probability=True,
    random_state=42
)

svm.fit(X_train_scaled, y_train)

print("SVM training completed successfully!")

# ============================================================
# 6. GENERATE PREDICTIONS
# ============================================================

preds = svm.predict(X_test_scaled)

# ============================================================
# 7. EVALUATE MODEL PERFORMANCE
# ============================================================

accuracy = accuracy_score(y_test, preds)

print("\n" + "=" * 50)
print("SVM MODEL EVALUATION")
print("=" * 50)

print(f"\nSVM Accuracy: {accuracy:.4f}")
print(f"SVM Accuracy Percentage: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        preds,
        zero_division=0
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, preds))

print("\nSVM evaluation completed!")

Dataset path: C:\Users\suyas\OneDrive\GIT\ML_LEARNING\kepler-exoplanet-ml\data\kepler_cleaned.csv

Dataset loaded successfully!
Dataset shape: (9564, 42)

,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag,target
0,1.000,0,0,0,0,9.488036,2.780000e-05,-2.780000e-05,170.538750,0.002160,...,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1
1,0.969,0,0,0,0,54.418383,2.480000e-04,-2.480000e-04,162.513840,0.003520,...,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1
2,0.000,0,0,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,1
3,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0
4,1.000,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1

Number of features: 41
Number of samples: 9564

Training samples: 7651
Testing samples: 1913

Feature scaling completed!

c:\Users\suyas\OneDrive\GIT\.venv\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVM training completed successfully!

==================================================
SVM MODEL EVALUATION
==================================================

SVM Accuracy: 0.9347
SVM Accuracy Percentage: 93.47%

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.95      0.94       968
           1       0.95      0.92      0.93       945

    accuracy                           0.93      1913
   macro avg       0.94      0.93      0.93      1913
weighted avg       0.93      0.93      0.93      1913

Confusion Matrix:
[[919  49]
 [ 76 869]]

SVM evaluation completed!

In [5]:

from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# 1. LOCATE AND LOAD THE DATASET
# ============================================================

cwd = Path.cwd()

possible_paths = [
    cwd / "data" / "kepler_cleaned.csv",
    cwd / "kepler-exoplanet-ml" / "data" / "kepler_cleaned.csv",
    cwd.parent / "data" / "kepler_cleaned.csv",
]

file_path = next(
    (path.resolve() for path in possible_paths if path.is_file()),
    None
)

if file_path is None:
    raise FileNotFoundError(
        f"Could not find kepler_cleaned.csv.\n"
        f"Current working directory: {cwd}\n"
        "Expected the CSV inside kepler-exoplanet-ml/data/."
    )

print("Dataset path:", file_path)

df = pd.read_csv(file_path)

print("\nDataset loaded successfully!")
print("Dataset shape:", df.shape)
display(df.head())

# ============================================================
# 2. PREPARE FEATURES AND TARGET
# ============================================================

if "target" not in df.columns:
    raise ValueError(
        "The dataset must contain a column named 'target'."
    )

X = df.drop(columns=["target"])
y = df["target"]

print("\nNumber of features:", X.shape[1])
print("Number of samples:", X.shape[0])

# ============================================================
# 3. SPLIT INTO TRAINING AND TESTING DATA
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# ============================================================
# 4. STANDARDIZE THE FEATURES
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nFeature scaling completed!")

# ============================================================
# 5. INITIALIZE AND TRAIN THE NEURAL NETWORK
# ============================================================

nn = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    max_iter=300,
    random_state=42
)

nn.fit(X_train_scaled, y_train)

print("\nNeural Network training completed!")

# ============================================================
# 6. GENERATE PREDICTIONS
# ============================================================

preds = nn.predict(X_test_scaled)

# ============================================================
# 7. EVALUATE MODEL PERFORMANCE
# ============================================================

accuracy = accuracy_score(y_test, preds)

print("\n" + "=" * 50)
print("NEURAL NETWORK MODEL EVALUATION")
print("=" * 50)

print(f"\nNeural Network Accuracy: {accuracy:.4f}")
print(f"Neural Network Accuracy Percentage: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        preds,
        zero_division=0
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, preds))

print("\nNeural Network evaluation completed!")

# ============================================================
# 8. TRAINING INFORMATION
# ============================================================

print("\nTraining iterations:", nn.n_iter_)
print("Training loss:", round(nn.loss_, 6))

if nn.n_iter_ == nn.max_iter:
    print(
        "Warning: The model may have reached max_iter "
        "before convergence. Check the convergence warning."
    )
else:
    print("The model stopped before reaching max_iter.")

Dataset path: C:\Users\suyas\OneDrive\GIT\ML_LEARNING\kepler-exoplanet-ml\data\kepler_cleaned.csv

Dataset loaded successfully!
Dataset shape: (9564, 42)

,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag,target
0,1.000,0,0,0,0,9.488036,2.780000e-05,-2.780000e-05,170.538750,0.002160,...,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1
1,0.969,0,0,0,0,54.418383,2.480000e-04,-2.480000e-04,162.513840,0.003520,...,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1
2,0.000,0,0,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,1
3,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0
4,1.000,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1

Number of features: 41
Number of samples: 9564

Training samples: 7651
Testing samples: 1913

Feature scaling completed!

Neural Network training completed!

==================================================
NEURAL NETWORK MODEL EVALUATION
==================================================

Neural Network Accuracy: 0.9817
Neural Network Accuracy Percentage: 98.17%

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       968
           1       0.98      0.99      0.98       945

    accuracy                           0.98      1913
   macro avg       0.98      0.98      0.98      1913
weighted avg       0.98      0.98      0.98      1913

Confusion Matrix:
[[945  23]
 [ 12 933]]

Neural Network evaluation completed!

Training iterations: 119
Training loss: 0.010694
The model stopped before reaching max_iter.

In [ ]:

from pathlib import Path

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# 1. LOCATE AND LOAD THE DATASET
# ============================================================

cwd = Path.cwd()

possible_paths = [
    cwd / "data" / "kepler_cleaned.csv",
    cwd / "kepler-exoplanet-ml" / "data" / "kepler_cleaned.csv",
    cwd.parent / "data" / "kepler_cleaned.csv",
]

file_path = next(
    (path.resolve() for path in possible_paths if path.is_file()),
    None
)

if file_path is None:
    raise FileNotFoundError(
        f"Could not find kepler_cleaned.csv.\n"
        f"Current working directory: {cwd}\n"
        "Expected the CSV inside kepler-exoplanet-ml/data/."
    )

print("Dataset path:", file_path)

df = pd.read_csv(file_path)

print("\nDataset loaded successfully!")
print("Dataset shape:", df.shape)
display(df.head())

# ============================================================
# 2. PREPARE FEATURES AND TARGET
# ============================================================

if "target" not in df.columns:
    raise ValueError("The dataset must contain a 'target' column.")

X = df.drop(columns=["target"])
y = df["target"]

print("\nNumber of features:", X.shape[1])
print("Number of samples:", X.shape[0])

# ============================================================
# 3. SPLIT INTO TRAINING AND TESTING DATA
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# ============================================================
# 4. STANDARDIZE THE FEATURES
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nFeature scaling completed!")

# ============================================================
# 5. DEFINE THE BASE ESTIMATORS
# ============================================================

base_estimators = [
    (
        "dt",
        DecisionTreeClassifier(
            max_depth=6,
            random_state=42
        )
    ),
    (
        "svm",
        SVC(
            probability=True,
            random_state=42
        )
    ),
    (
        "nn",
        MLPClassifier(
            hidden_layer_sizes=(64, 32),
            max_iter=300,
            random_state=42
        )
    )
]

print("\nBase estimators defined:")
print("1. Decision Tree")
print("2. Support Vector Machine")
print("3. Neural Network")

# ============================================================
# 6. CREATE THE STACKING ENSEMBLE
# ============================================================

stacking_ensemble = StackingClassifier(
    estimators=base_estimators,
    final_estimator=LogisticRegression(
        max_iter=1000,
        random_state=42
    ),
    cv=5
)

# ============================================================
# 7. TRAIN THE META-MODEL
# ============================================================

print("\nTraining Stacking Ensemble...")
stacking_ensemble.fit(X_train_scaled, y_train)

print("Stacking Ensemble training completed!")

# ============================================================
# 8. GENERATE PREDICTIONS
# ============================================================

preds = stacking_ensemble.predict(X_test_scaled)

# ============================================================
# 9. EVALUATE MODEL PERFORMANCE
# ============================================================

accuracy = accuracy_score(y_test, preds)

print("\n" + "=" * 55)
print("STACKING ENSEMBLE MODEL EVALUATION")
print("=" * 55)

print(f"\nStacked Ensemble Accuracy: {accuracy:.4f}")
print(f"Stacked Ensemble Accuracy: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        preds,
        zero_division=0
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, preds))

print("\nMeta-model evaluation completed!")